# -*- coding: utf-8 -*-
"""data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZ3nX_MUdOSlCw6lFiVrNA3zJr2H6L3y
"""

import pandas as pd

# 1. EXTRACT: Load the raw restaurant transaction data
print("Loading raw transaction data...")
df = pd.read_csv('/restaurant_sales.csv')

# Standardize column names (fixes capitalization and spacing issues automatically)
df.columns = df.columns.str.strip().str.lower()

# 2. TRANSFORM: Clean missing values and standardize dates
print(f"Initial row count: {len(df)}")
df_clean = df.dropna().drop_duplicates()
df_clean['date'] = pd.to_datetime(df_clean['date'])

# 3. BUSINESS LOGIC: Feature Engineering (Profit Margins & Tiers)
df_clean['profit_margin'] = df_clean['profit'] / df_clean['net_revenue']

def assign_profit_tier(margin):
    if margin >= 0.40:
        return 'Tier A (High Margin)'
    elif margin >= 0.25:
        return 'Tier B (Medium Margin)'
    else:
        return 'Tier C (Low Margin)'

df_clean['profit_tier'] = df_clean['profit_margin'].apply(assign_profit_tier)

# 4. LOAD: Export the enhanced dataset for reporting
output_filename = 'restaurant_sales_analyzed.csv'
df_clean.to_csv(output_filename, index=False)

print(f"Data processing complete! Cleaned and tiered data saved to {output_filename}.")
print(f"Final row count: {len(df_clean)}")